version: "3"

services:
  php:
    build:
      context: ./api
      target: app_php
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-14}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|caddy|${TRUSTED_MIDDLEWARE:-souin}$$
      TRUSTED_MIDDLEWARE: ${TRUSTED_MIDDLEWARE:-souin}
      MAILER_DSN: ${MAILER_DSN:-smtp://mailhog:1025}
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}

  pwa:
    build:
      context: ./pwa
      target: prod
      args:
        NEXT_PUBLIC_ENTRYPOINT: http://caddy
        API_URL: ${API_URL:-http://localhost}
        CONTACT_EMAIL: ${CONTACT_EMAIL:-my@email.com}
        ADDRESS: ${ADDRESS:-somewhere}
    environment:
      NEXT_PUBLIC_ENTRYPOINT: http://caddy
      API_URL: ${API_URL:-http://localhost}
      CONTACT_EMAIL: ${CONTACT_EMAIL:-my@email.com}
      ADDRESS: ${ADDRESS:-somewhere}

  caddy:
    build:
      context: api/
      target: app_caddy
    depends_on:
      - php
      # - pwa
    environment:
      PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME:-localhost:80, localhost:443}, caddy:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_MIDDLEWARE: ${TRUSTED_MIDDLEWARE:-souin}
      SEMAPHORE_URL: ${SEMAPHORE_URL:-http://semaphore:3000}
      SEMAPHORE_USERNAME: ${SEMAPHORE_USER}
      SEMAPHORE_PASSWORD: ${SEMAPHORE_PASSWORD}
      PROJECT_ID: ${PROJECT_ID:-1}
      TEMPLATE_ID: ${TEMPLATE_ID:-1}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-app}
    volumes:
      - db_data:/var/lib/postgresql/data
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./api/docker/db/data:/var/lib/postgresql/data
  ###< doctrine/doctrine-bundle ###

  # Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
  ###> symfony/mercure-bundle ###
  ###< symfony/mercure-bundle ###

  semaphore:
    image: semaphoreui/semaphore:latest
    volumes:
      - ./api/middleware/pkg/deployer/semaphore:/tmp/semaphore:rw,delegated
    environment:
      SEMAPHORE_DB_USER: ${POSTGRES_USER:-app}
      SEMAPHORE_DB_PASS: ${POSTGRES_PASSWORD:-!ChangeMe!}
      SEMAPHORE_DB_HOST: database
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: ${POSTGRES_DB:-semaphore}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/playbooks
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_USER}
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: ${SEMAPHORE_USER}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
    depends_on:
      - database

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  ###> doctrine/doctrine-bundle ###
  db_data:
###< doctrine/doctrine-bundle ###
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
