- hosts: manager
  vars:
    label: '{{ LABEL }}'
    deploy_name: cache-handler
    basepath: share/cache-handler
  tasks:
    - name: Init swarm on the first node
      shell: "docker node ls | grep Leader | awk '{print $1}'"
      register: result

    - name: Retrieve the Caddyfile.j2 from the server
      copy:
        src: '{{ basepath }}/Caddyfile.j2'
        dest: ./Caddyfile.j2
        remote_src: yes

    - name: Generate Caddyfile
      template:
        src: Caddyfile.j2
        dest: '{{ basepath }}/Caddyfile-{{ label }}'
      vars:
        domain: '{{ CURRENT_DOMAIN }}'
        configuration: '{{ CONFIGURATION }}'

    - name: Set manager token
      set_fact:
        main_node: "{{ hostvars['manager0'].result.stdout_lines[0] }}"

    - name: Add {{ label }} label for main node
      shell: 'docker node update --label-add {{ label }}.{{ label }}-data=true {{ main_node }}'

    - name: Deploy {{ label }}
      shell: 'docker stack deploy -c {{ basepath }}/docker-compose.handler.yml {{ deploy_name }}_{{ label }}'
      environment:
        - DOMAIN: '{{ CURRENT_DOMAIN }}'
        - LABEL: '{{ label }}'
      args:
        chdir: $HOME
