controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
auth:
    path: /auth
    methods: [ 'POST' ]
    
activation:
    path: /activation
    methods: [ 'POST' ]
    controller: App\Action\ActivationAction
    
update-password:
    path: /update-password
    methods: [ 'PATCH' ]
    controller: App\Action\ChangePasswordAction
